name: Nightlies

on:
  push:
    branches:
      - main
    tags:     # Trigger on tags as well
      - '*.*.*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          show-progress: true,

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - run: |
          dotnet restore
          dotnet build EloReputation.csproj --no-restore
          dotnet publish EloReputation.csproj --no-build --no-restore

      - name: Upload Nightly Artifact
        if: github.event_name != 'push' || contains(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4.0.0
        with:
          name: elorep-nightly
          path: build/
          if-no-files-found: error
